# Generated by Django 3.2.20 on 2023-08-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.TextField(max_length=200)),
                ('Description', models.TextField(max_length=300)),
                ('Price', models.CharField(max_length=50)),
                ('Model_name', models.TextField(max_length=300)),
                ('Color', models.TextField(max_length=300)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('publish', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.TextField(max_length=200)),
                ('Description', models.TextField(max_length=300)),
                ('Price', models.CharField(max_length=50)),
                ('Model_name', models.TextField(max_length=300)),
                ('Color', models.TextField(max_length=300)),
                ('Size', models.TextField(max_length=100)),
                ('publish', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
