# Generated by Django 3.2.20 on 2023-08-23 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bags_products_shoes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bags',
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
        migrations.AddField(
            model_name='products',
            name='Brand',
            field=models.TextField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='products',
            name='Color',
            field=models.TextField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='products',
            name='Description',
            field=models.TextField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='products',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=' ', max_length=1),
        ),
        migrations.AddField(
            model_name='products',
            name='Model_name',
            field=models.TextField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='products',
            name='Price',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='Size',
            field=models.TextField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.CharField(default=' ', max_length=400),
        ),
        migrations.AddField(
            model_name='products',
            name='publish',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
