# Generated by Django 3.2.20 on 2023-08-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230823_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Image',
            field=models.ImageField(default=' ', upload_to=''),
            preserve_default=False,
        ),
    ]
