# Generated by Django 3.2.20 on 2023-08-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Model_name',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_category',
            new_name='product_cname',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Size',
            new_name='size',
        ),
    ]
