# Generated by Django 3.2.20 on 2023-08-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230825_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default=' ', max_length=400)),
                ('brand', models.TextField(default=' ', max_length=200)),
                ('description', models.TextField(default=' ', max_length=300)),
                ('price', models.CharField(default=' ', max_length=50)),
                ('model_name', models.TextField(default=' ', max_length=300)),
                ('color', models.TextField(default=' ', max_length=300)),
                ('size', models.TextField(default=' ', max_length=100)),
                ('publish', models.TimeField(auto_now_add=True)),
                ('image', models.ImageField(default='blank.webp', upload_to='product_images')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=' ', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
